apiVersion: v1
baseDomain: ocp.isvlab.vmware.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 16
      coresPerSocket: 8
      memoryMB: 32768
  replicas: 4
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 4
      memoryMB: 16384
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp413-c1
networking:
  clusterNetwork:
  - cidr: 10.64.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.16.62.0/26
  networkType: antrea
  serviceNetwork:
  - 192.168.64.0/18
platform:
  vsphere:
    apiVIPs:
    - 172.16.62.5
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: wdc-m01-vc01.vcf02.isvlab.vmware.com
      topology:
        computeCluster: /wdc-m01-dc01/host/wdc-m01-cl01
        datacenter: wdc-m01-dc01
        datastore: /wdc-m01-dc01/datastore/wdc-m01-cl01-ds-vsan01
        networks:
        - ocp-segment
        resourcePool: /wdc-m01-dc01/host/wdc-m01-cl01/Resources/ocp413-c1-antrea
      zone: generated-zone
    ingressVIPs:
    - 172.16.62.6
    vcenters:
    - datacenters:
      - wdc-m01-dc01
      password: ********
      port: 443
      server: wdc-m01-vc01.vcf02.isvlab.vmware.com
      user: administrator@vsphere.local
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"********...","email":"********@broadcom.com"}}}'
sshKey: |
  ssh-ed25519 ********