apiVersion: v1
baseDomain: vmware.env.com
proxy:
  httpProxy: http://10.244.x.x:3128
  noProxy: 10.0.0.0/8,192.168.0.0/16,172.0.0.0/11
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp-c0
networking:
  networkType: ncp
  clusterNetwork:
  - cidr: 192.168.16.0/20
    hostPrefix: 24
  machineCIDR: 192.168.3.0/24
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: 172.31.x.x
    username: administrator@vsphere.local
    password: xxxx
    datacenter: datacenter1
    defaultDatastore: VxRail-Virtual-SAN-Datastore-b487f80c-1f4f-4606-9e54-c447fb0a1951
fips: false
pullSecret: 'xxxx' 
sshKey: 'ssh-rsa xxxx'