apiVersion: v1
kind: Pod
metadata:
  name: redis-leader
  labels:
app: redis
spec:
  containers:
    - name: leader
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/redis
      env:
        - name: LEADER
          value: “true”
      volumeMounts:
        - mountPath: /mnt/fileserver
          name: redis-pvc
      ports:
        - containerPort: 6379
  volumes:
    - name: redis-pvc
      persistentVolumeClaim:
        claimName: fileserver-claim
        readOnly: false