apiVersion: v1
kind: ConfigMap
metadata:
  name: nsx-ncp-operator-config
  namespace: nsx-system-operator
data:
  ncp.ini: |
    [vc]

    [coe]
    adaptor = openshift4
    cluster = ocp-c0

    [DEFAULT]

    [nsx_v3]
    policy_nsxapi = True
    nsx_api_managers = 172.31.x.x,172.31.x.x,172.31.x.x
    nsx_api_user = admin
    nsx_api_password = xxxx
    insecure = True
    log_firewall_traffic = DENY
    use_native_loadbalancer = True
    pool_algorithm = WEIGHTED_ROUND_ROBIN
    external_ip_pools = 172.31.x.x/27
    tier0_gateway = env1-t0
    single_tier_topology = True
    overlay_tz = 61372b06-d540-4902-aea8-3075563a13d6
    edge_cluster = 4bbae32e-56c7-42ea-bae4-bf191875e694

    [ha]

    [k8s]
    apiserver_host_ip = api-int.ocp-c0.VMWARE.ENV.COM
    apiserver_host_port = 6443
    client_token_file = /var/run/secrets/kubernetes.io/serviceaccount/token
    ca_file = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    baseline_policy_type = allow_cluster
    enable_multus = False
    process_oc_network = False

    [nsx_kube_proxy]

    [nsx_node_agent]
    ovs_bridge = br-int
    ovs_uplink_port = ens192